"""add core administration

Revision ID: 12daf745db21
Revises: 0001_foundation
Create Date: 2026-08-01 15:23:06.815630
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "12daf745db21"
down_revision: str | Sequence[str] | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hauliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("contact_name", sa.String(length=150), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("default_cost_per_km", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("minimum_load_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("waiting_hourly_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fuel_surcharge_percent", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "default_cost_per_km >= 0", name=op.f("ck_hauliers_cost_per_km_nonnegative")
        ),
        sa.CheckConstraint(
            "fuel_surcharge_percent >= 0", name=op.f("ck_hauliers_fuel_surcharge_nonnegative")
        ),
        sa.CheckConstraint(
            "minimum_load_cost >= 0", name=op.f("ck_hauliers_minimum_load_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "waiting_hourly_cost >= 0", name=op.f("ck_hauliers_waiting_cost_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hauliers")),
        sa.UniqueConstraint("name", name=op.f("uq_hauliers_name")),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "location_type",
            sa.Enum(
                "SITE",
                "YARD",
                "DEPOT",
                "WORKSHOP",
                "AIRPORT",
                "FERRY_PORT",
                "OTHER",
                name="locationtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("address_line_1", sa.String(length=200), nullable=True),
        sa.Column("address_line_2", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("postcode", sa.String(length=30), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("geocoding_provider", sa.String(length=50), nullable=True),
        sa.Column("geocoding_place_id", sa.String(length=200), nullable=True),
        sa.Column("geocoded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_notes", sa.Text(), nullable=True),
        sa.Column("hgv_notes", sa.Text(), nullable=True),
        sa.Column("receiving_notes", sa.Text(), nullable=True),
        sa.Column("default_unload_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "default_unload_duration_minutes >= 0",
            name=op.f("ck_locations_unload_duration_nonnegative"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name=op.f("ck_locations_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name=op.f("ck_locations_longitude_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=True)
    op.create_table(
        "lorry_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("section_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pole_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("ancillary_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payload_kg", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("passenger_capacity", sa.Integer(), nullable=False),
        sa.Column("default_cost_per_km", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("minimum_load_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "ancillary_capacity_units >= 0", name=op.f("ck_lorry_types_ancillary_units_nonnegative")
        ),
        sa.CheckConstraint(
            "default_cost_per_km >= 0", name=op.f("ck_lorry_types_cost_per_km_nonnegative")
        ),
        sa.CheckConstraint(
            "minimum_load_cost >= 0", name=op.f("ck_lorry_types_minimum_load_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "passenger_capacity >= 0", name=op.f("ck_lorry_types_passenger_capacity_nonnegative")
        ),
        sa.CheckConstraint("payload_kg >= 0", name=op.f("ck_lorry_types_payload_nonnegative")),
        sa.CheckConstraint(
            "pole_capacity_units >= 0", name=op.f("ck_lorry_types_pole_units_nonnegative")
        ),
        sa.CheckConstraint(
            "section_capacity_units >= 0", name=op.f("ck_lorry_types_section_units_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lorry_types")),
        sa.UniqueConstraint("name", name=op.f("uq_lorry_types_name")),
    )
    op.create_table(
        "tent_families",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tent_families")),
    )
    op.create_index(op.f("ix_tent_families_name"), "tent_families", ["name"], unique=True)
    op.create_table(
        "crew_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("employment_type", sa.String(length=100), nullable=False),
        sa.Column("hourly_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("overtime_hourly_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("travel_hourly_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("daily_allowance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("can_drive_van", sa.Boolean(), nullable=False),
        sa.Column("can_drive_hgv", sa.Boolean(), nullable=False),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column("home_location_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "daily_allowance >= 0", name=op.f("ck_crew_members_daily_allowance_nonnegative")
        ),
        sa.CheckConstraint(
            "hourly_cost >= 0", name=op.f("ck_crew_members_hourly_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "overtime_hourly_cost >= 0", name=op.f("ck_crew_members_overtime_cost_nonnegative")
        ),
        sa.CheckConstraint(
            "travel_hourly_cost >= 0", name=op.f("ck_crew_members_travel_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["home_location_id"],
            ["locations.id"],
            name=op.f("fk_crew_members_home_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_members")),
    )
    op.create_index(op.f("ix_crew_members_name"), "crew_members", ["name"], unique=False)
    op.create_table(
        "equipment_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("tent_family_id", sa.Integer(), nullable=True),
        sa.Column(
            "tracking_mode",
            sa.Enum("INDIVIDUAL", "QUANTITY", name="trackingmode", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("section_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pole_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("ancillary_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "default_build_stage",
            sa.Enum(
                "SITE_PREPARATION",
                "POLES_AND_ANCHORS",
                "MAIN_SECTIONS",
                "COMPLETION_AND_ANCILLARY",
                "MAINTENANCE",
                "STRIKE",
                name="buildstage",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("maintenance_interval_days", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "ancillary_capacity_units >= 0",
            name=op.f("ck_equipment_types_ancillary_units_nonnegative"),
        ),
        sa.CheckConstraint(
            "maintenance_interval_days IS NULL OR maintenance_interval_days >= 0",
            name=op.f("ck_equipment_types_maintenance_interval_nonnegative"),
        ),
        sa.CheckConstraint(
            "pole_capacity_units >= 0", name=op.f("ck_equipment_types_pole_units_nonnegative")
        ),
        sa.CheckConstraint(
            "section_capacity_units >= 0", name=op.f("ck_equipment_types_section_units_nonnegative")
        ),
        sa.CheckConstraint("weight_kg >= 0", name=op.f("ck_equipment_types_weight_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tent_family_id"],
            ["tent_families.id"],
            name=op.f("fk_equipment_types_tent_family_id_tent_families"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_types")),
    )
    op.create_index(op.f("ix_equipment_types_code"), "equipment_types", ["code"], unique=True)
    op.create_table(
        "lorries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_or_name", sa.String(length=100), nullable=False),
        sa.Column("lorry_type_id", sa.Integer(), nullable=False),
        sa.Column("haulier_id", sa.Integer(), nullable=True),
        sa.Column(
            "ownership_type",
            sa.Enum(
                "OWNED", "HIRED", "SUPPLIER", name="ownershiptype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("home_location_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["haulier_id"], ["hauliers.id"], name=op.f("fk_lorries_haulier_id_hauliers")
        ),
        sa.ForeignKeyConstraint(
            ["home_location_id"],
            ["locations.id"],
            name=op.f("fk_lorries_home_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["lorry_type_id"], ["lorry_types.id"], name=op.f("fk_lorries_lorry_type_id_lorry_types")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lorries")),
        sa.UniqueConstraint("registration_or_name", name=op.f("uq_lorries_registration_or_name")),
    )
    op.create_table(
        "tent_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tent_family_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("pole_count", sa.Integer(), nullable=False),
        sa.Column("width_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("length_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("default_build_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("default_strike_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("minimum_crew", sa.Integer(), nullable=False),
        sa.Column("preferred_crew", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "default_build_hours >= 0", name=op.f("ck_tent_configurations_build_hours_nonnegative")
        ),
        sa.CheckConstraint(
            "default_strike_hours >= 0",
            name=op.f("ck_tent_configurations_strike_hours_nonnegative"),
        ),
        sa.CheckConstraint(
            "minimum_crew >= 0", name=op.f("ck_tent_configurations_minimum_crew_nonnegative")
        ),
        sa.CheckConstraint(
            "pole_count > 0", name=op.f("ck_tent_configurations_pole_count_positive")
        ),
        sa.CheckConstraint(
            "preferred_crew >= minimum_crew",
            name=op.f("ck_tent_configurations_preferred_crew_minimum"),
        ),
        sa.ForeignKeyConstraint(
            ["tent_family_id"],
            ["tent_families.id"],
            name=op.f("fk_tent_configurations_tent_family_id_tent_families"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tent_configurations")),
        sa.UniqueConstraint(
            "tent_family_id", "name", name=op.f("uq_tent_configurations_tent_family_id")
        ),
    )
    op.create_table(
        "vans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registration_or_name", sa.String(length=100), nullable=False),
        sa.Column("passenger_capacity", sa.Integer(), nullable=False),
        sa.Column("cargo_capacity_units", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("home_location_id", sa.Integer(), nullable=False),
        sa.Column(
            "ownership_type",
            sa.Enum(
                "OWNED", "HIRED", "SUPPLIER", name="ownershiptype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("cost_per_km", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "cargo_capacity_units >= 0", name=op.f("ck_vans_cargo_capacity_nonnegative")
        ),
        sa.CheckConstraint("cost_per_km >= 0", name=op.f("ck_vans_cost_per_km_nonnegative")),
        sa.CheckConstraint(
            "passenger_capacity >= 0", name=op.f("ck_vans_passenger_capacity_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["home_location_id"], ["locations.id"], name=op.f("fk_vans_home_location_id_locations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vans")),
        sa.UniqueConstraint("registration_or_name", name=op.f("uq_vans_registration_or_name")),
    )
    op.create_table(
        "crew_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crew_member_id", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.Date(), nullable=False),
        sa.Column("end_at", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UNAVAILABLE",
                "LEAVE",
                "TRAINING",
                "RESTRICTED",
                "AVAILABLE_OVERRIDE",
                name="crewavailabilitystatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("end_at >= start_at", name=op.f("ck_crew_availability_date_order")),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_crew_availability_crew_member_id_crew_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_availability")),
    )
    op.create_index(
        op.f("ix_crew_availability_crew_member_id"),
        "crew_availability",
        ["crew_member_id"],
        unique=False,
    )
    op.create_table(
        "equipment_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_code", sa.String(length=50), nullable=False),
        sa.Column("equipment_type_id", sa.Integer(), nullable=False),
        sa.Column("variant", sa.String(length=100), nullable=True),
        sa.Column("generation", sa.String(length=100), nullable=True),
        sa.Column("initial_location_id", sa.Integer(), nullable=True),
        sa.Column("current_status", sa.String(length=50), nullable=False),
        sa.Column("serviceable", sa.Boolean(), nullable=False),
        sa.Column("commissioned_date", sa.Date(), nullable=True),
        sa.Column("retired_date", sa.Date(), nullable=True),
        sa.Column("replacement_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "replacement_value IS NULL OR replacement_value >= 0",
            name=op.f("ck_equipment_assets_replacement_value_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_type_id"],
            ["equipment_types.id"],
            name=op.f("fk_equipment_assets_equipment_type_id_equipment_types"),
        ),
        sa.ForeignKeyConstraint(
            ["initial_location_id"],
            ["locations.id"],
            name=op.f("fk_equipment_assets_initial_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_assets")),
    )
    op.create_index(
        op.f("ix_equipment_assets_asset_code"), "equipment_assets", ["asset_code"], unique=True
    )
    op.create_table(
        "tent_configuration_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tent_configuration_id", sa.Integer(), nullable=False),
        sa.Column("equipment_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "required_stage",
            sa.Enum(
                "SITE_PREPARATION",
                "POLES_AND_ANCHORS",
                "MAIN_SECTIONS",
                "COMPLETION_AND_ANCILLARY",
                "MAINTENANCE",
                "STRIKE",
                name="buildstage",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("individually_assignable", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_tent_configuration_requirements_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["equipment_type_id"],
            ["equipment_types.id"],
            name=op.f("fk_tent_configuration_requirements_equipment_type_id_equipment_types"),
        ),
        sa.ForeignKeyConstraint(
            ["tent_configuration_id"],
            ["tent_configurations.id"],
            name=op.f(
                "fk_tent_configuration_requirements_tent_configuration_id_tent_configurations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tent_configuration_requirements")),
        sa.UniqueConstraint(
            "tent_configuration_id",
            "equipment_type_id",
            "required_stage",
            name=op.f("uq_tent_configuration_requirements_tent_configuration_id"),
        ),
    )
    op.create_table(
        "tentmasters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("lead_crew_member_id", sa.Integer(), nullable=True),
        sa.Column("home_location_id", sa.Integer(), nullable=True),
        sa.Column("default_van_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_van_id"], ["vans.id"], name=op.f("fk_tentmasters_default_van_id_vans")
        ),
        sa.ForeignKeyConstraint(
            ["home_location_id"],
            ["locations.id"],
            name=op.f("fk_tentmasters_home_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["lead_crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_tentmasters_lead_crew_member_id_crew_members"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tentmasters")),
        sa.UniqueConstraint("name", name=op.f("uq_tentmasters_name")),
    )
    op.create_table(
        "tentmaster_memberships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tentmaster_id", sa.Integer(), nullable=False),
        sa.Column("crew_member_id", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.Date(), nullable=False),
        sa.Column("end_at", sa.Date(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "end_at IS NULL OR end_at >= start_at",
            name=op.f("ck_tentmaster_memberships_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_tentmaster_memberships_crew_member_id_crew_members"),
        ),
        sa.ForeignKeyConstraint(
            ["tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_tentmaster_memberships_tentmaster_id_tentmasters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tentmaster_memberships")),
    )
    op.create_index(
        op.f("ix_tentmaster_memberships_crew_member_id"),
        "tentmaster_memberships",
        ["crew_member_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tentmaster_memberships_crew_member_id"), table_name="tentmaster_memberships"
    )
    op.drop_table("tentmaster_memberships")
    op.drop_table("tentmasters")
    op.drop_table("tent_configuration_requirements")
    op.drop_index(op.f("ix_equipment_assets_asset_code"), table_name="equipment_assets")
    op.drop_table("equipment_assets")
    op.drop_index(op.f("ix_crew_availability_crew_member_id"), table_name="crew_availability")
    op.drop_table("crew_availability")
    op.drop_table("vans")
    op.drop_table("tent_configurations")
    op.drop_table("lorries")
    op.drop_index(op.f("ix_equipment_types_code"), table_name="equipment_types")
    op.drop_table("equipment_types")
    op.drop_index(op.f("ix_crew_members_name"), table_name="crew_members")
    op.drop_table("crew_members")
    op.drop_index(op.f("ix_tent_families_name"), table_name="tent_families")
    op.drop_table("tent_families")
    op.drop_table("lorry_types")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_table("locations")
    op.drop_table("hauliers")
    # ### end Alembic commands ###
