"""add jobs requirements and phases

Revision ID: 2afbf5e551ad
Revises: 12daf745db21
Create Date: 2026-08-01 15:57:38.582381
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2afbf5e551ad"
down_revision: str | Sequence[str] | None = "12daf745db21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column(
            "commercial_status",
            sa.Enum(
                "ENQUIRY",
                "QUOTE_IN_PREPARATION",
                "QUOTED",
                "DEPOSIT_REQUESTED",
                "DEPOSIT_RECEIVED",
                "CONFIRMED",
                "CANCELLED",
                "COMPLETED",
                name="commercialstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "planning_status",
            sa.Enum(
                "NOT_PLANNED",
                "PROVISIONAL_PLAN",
                "FEASIBLE",
                "AT_RISK",
                "CONFLICT",
                "PLANNER_APPROVED",
                "OPERATIONALLY_LOCKED",
                name="planningstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("confidence_percent", sa.Integer(), nullable=True),
        sa.Column("contract_revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("site_access_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("must_be_up_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("show_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("show_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("strike_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("site_clear_by", sa.DateTime(timezone=True), nullable=True),
        sa.Column("maintenance_cover_required", sa.Boolean(), nullable=False),
        sa.Column("catering_arrangement", sa.Text(), nullable=True),
        sa.Column("accommodation_arrangement", sa.Text(), nullable=True),
        sa.Column("ground_type", sa.String(length=100), nullable=True),
        sa.Column("local_crew_supplied", sa.Integer(), nullable=False),
        sa.Column("local_crew_required", sa.Integer(), nullable=False),
        sa.Column("build_scope", sa.Text(), nullable=True),
        sa.Column("strike_scope", sa.Text(), nullable=True),
        sa.Column("operational_notes", sa.Text(), nullable=True),
        sa.Column("commercial_notes", sa.Text(), nullable=True),
        sa.Column("deposit_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence_percent IS NULL OR confidence_percent BETWEEN 0 AND 100",
            name=op.f("ck_jobs_confidence_range"),
        ),
        sa.CheckConstraint(
            "contract_revenue >= 0", name=op.f("ck_jobs_contract_revenue_nonnegative")
        ),
        sa.CheckConstraint(
            "local_crew_required >= 0", name=op.f("ck_jobs_local_crew_required_nonnegative")
        ),
        sa.CheckConstraint(
            "local_crew_supplied >= 0", name=op.f("ck_jobs_local_crew_supplied_nonnegative")
        ),
        sa.CheckConstraint(
            "must_be_up_at >= site_access_at", name=op.f("ck_jobs_access_before_up")
        ),
        sa.CheckConstraint(
            "show_end_at IS NULL OR show_start_at IS NULL OR show_end_at >= show_start_at",
            name=op.f("ck_jobs_show_date_order"),
        ),
        sa.CheckConstraint(
            "site_clear_by IS NULL OR site_clear_by >= strike_available_at",
            name=op.f("ck_jobs_strike_before_clear"),
        ),
        sa.CheckConstraint(
            "strike_available_at >= must_be_up_at", name=op.f("ck_jobs_up_before_strike")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.id"], name=op.f("fk_jobs_location_id_locations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_commercial_status"), "jobs", ["commercial_status"], unique=False)
    op.create_index(op.f("ix_jobs_job_code"), "jobs", ["job_code"], unique=True)
    op.create_index(op.f("ix_jobs_location_id"), "jobs", ["location_id"], unique=False)
    op.create_index(op.f("ix_jobs_name"), "jobs", ["name"], unique=False)
    op.create_index(op.f("ix_jobs_planning_status"), "jobs", ["planning_status"], unique=False)
    op.create_index(op.f("ix_jobs_site_access_at"), "jobs", ["site_access_at"], unique=False)
    op.create_index(
        op.f("ix_jobs_strike_available_at"), "jobs", ["strike_available_at"], unique=False
    )
    op.create_table(
        "job_tent_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("tent_configuration_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("custom_name", sa.String(length=200), nullable=True),
        sa.Column("build_start_override", sa.DateTime(timezone=True), nullable=True),
        sa.Column("build_duration_override_hours", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "strike_duration_override_hours", sa.Numeric(precision=8, scale=2), nullable=True
        ),
        sa.Column("required_crew_override", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_job_tent_requirements_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_tent_requirements_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tent_configuration_id"],
            ["tent_configurations.id"],
            name=op.f("fk_job_tent_requirements_tent_configuration_id_tent_configurations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_tent_requirements")),
    )
    op.create_index(
        op.f("ix_job_tent_requirements_job_id"), "job_tent_requirements", ["job_id"], unique=False
    )
    op.create_table(
        "job_equipment_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("job_tent_requirement_id", sa.Integer(), nullable=True),
        sa.Column("equipment_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity_required", sa.Integer(), nullable=False),
        sa.Column("required_on_site_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("releasable_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "required_stage",
            sa.Enum(
                "SITE_PREPARATION",
                "POLES_AND_ANCHORS",
                "MAIN_SECTIONS",
                "COMPLETION_AND_ANCILLARY",
                "MAINTENANCE",
                "STRIKE",
                name="buildstage",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("GENERATED", "MANUAL", name="requirementsource", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "UNRESOLVED",
                "PARTIALLY_ASSIGNED",
                "ASSIGNED",
                "CONFLICT",
                name="requirementstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "quantity_required > 0", name=op.f("ck_job_equipment_requirements_quantity_positive")
        ),
        sa.CheckConstraint(
            "releasable_at >= required_on_site_at",
            name=op.f("ck_job_equipment_requirements_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_type_id"],
            ["equipment_types.id"],
            name=op.f("fk_job_equipment_requirements_equipment_type_id_equipment_types"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_equipment_requirements_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_tent_requirement_id"],
            ["job_tent_requirements.id"],
            name=op.f(
                "fk_job_equipment_requirements_job_tent_requirement_id_job_tent_requirements"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_equipment_requirements")),
        sa.UniqueConstraint(
            "job_id",
            "equipment_type_id",
            "required_stage",
            "source",
            name=op.f("uq_job_equipment_requirements_job_id"),
        ),
    )
    op.create_index(
        op.f("ix_job_equipment_requirements_job_id"),
        "job_equipment_requirements",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_equipment_requirements_releasable_at"),
        "job_equipment_requirements",
        ["releasable_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_equipment_requirements_required_on_site_at"),
        "job_equipment_requirements",
        ["required_on_site_at"],
        unique=False,
    )
    op.create_table(
        "job_phases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "phase_type",
            sa.Enum(
                "SITE_PREP",
                "BUILD",
                "HANDOVER",
                "SHOW",
                "MAINTENANCE",
                "STRIKE",
                "CLEAR_SITE",
                "OTHER",
                name="phasetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("tentmaster_id", sa.Integer(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("required_headcount", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "GENERATED",
                "MANUAL",
                "SUGGESTED",
                name="recordsource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_job_phases_date_order")),
        sa.CheckConstraint(
            "required_headcount >= 0", name=op.f("ck_job_phases_headcount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_phases_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_job_phases_tentmaster_id_tentmasters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_phases")),
    )
    op.create_index(op.f("ix_job_phases_end_at"), "job_phases", ["end_at"], unique=False)
    op.create_index(op.f("ix_job_phases_job_id"), "job_phases", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_phases_phase_type"), "job_phases", ["phase_type"], unique=False)
    op.create_index(op.f("ix_job_phases_start_at"), "job_phases", ["start_at"], unique=False)
    op.create_index(
        op.f("ix_job_phases_tentmaster_id"), "job_phases", ["tentmaster_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_phases_tentmaster_id"), table_name="job_phases")
    op.drop_index(op.f("ix_job_phases_start_at"), table_name="job_phases")
    op.drop_index(op.f("ix_job_phases_phase_type"), table_name="job_phases")
    op.drop_index(op.f("ix_job_phases_job_id"), table_name="job_phases")
    op.drop_index(op.f("ix_job_phases_end_at"), table_name="job_phases")
    op.drop_table("job_phases")
    op.drop_index(
        op.f("ix_job_equipment_requirements_required_on_site_at"),
        table_name="job_equipment_requirements",
    )
    op.drop_index(
        op.f("ix_job_equipment_requirements_releasable_at"), table_name="job_equipment_requirements"
    )
    op.drop_index(
        op.f("ix_job_equipment_requirements_job_id"), table_name="job_equipment_requirements"
    )
    op.drop_table("job_equipment_requirements")
    op.drop_index(op.f("ix_job_tent_requirements_job_id"), table_name="job_tent_requirements")
    op.drop_table("job_tent_requirements")
    op.drop_index(op.f("ix_jobs_strike_available_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_site_access_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_planning_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_name"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_location_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_job_code"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_commercial_status"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
