"""add route cache

Revision ID: 63dda1ae9a9e
Revises: 721a9d1d7dab
Create Date: 2026-08-01 16:18:33.435796
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.database import AwareDateTime

revision: str = "63dda1ae9a9e"
down_revision: str | Sequence[str] | None = "721a9d1d7dab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("origin_location_id", sa.Integer(), nullable=False),
        sa.Column("destination_location_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_profile", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("distance_km", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("driving_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("calculated_at", AwareDateTime(), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.CheckConstraint("distance_km >= 0", name=op.f("ck_route_cache_distance_nonnegative")),
        sa.CheckConstraint(
            "driving_duration_minutes >= 0", name=op.f("ck_route_cache_duration_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
            name=op.f("fk_route_cache_destination_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
            name=op.f("fk_route_cache_origin_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_route_cache")),
        sa.UniqueConstraint("cache_key", name=op.f("uq_route_cache_cache_key")),
    )
    op.create_index(op.f("ix_route_cache_cache_key"), "route_cache", ["cache_key"], unique=True)
    op.create_index(
        op.f("ix_route_cache_destination_location_id"),
        "route_cache",
        ["destination_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_route_cache_origin_location_id"),
        "route_cache",
        ["origin_location_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_route_cache_origin_location_id"), table_name="route_cache")
    op.drop_index(op.f("ix_route_cache_destination_location_id"), table_name="route_cache")
    op.drop_index(op.f("ix_route_cache_cache_key"), table_name="route_cache")
    op.drop_table("route_cache")
    # ### end Alembic commands ###
