"""add equipment movements and loads

Revision ID: 721a9d1d7dab
Revises: 8ffe2eede605
Create Date: 2026-08-01 16:15:35.759095
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.database import AwareDateTime

revision: str = "721a9d1d7dab"
down_revision: str | Sequence[str] | None = "8ffe2eede605"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movement_code", sa.String(length=50), nullable=False),
        sa.Column("origin_location_id", sa.Integer(), nullable=False),
        sa.Column("destination_location_id", sa.Integer(), nullable=False),
        sa.Column("depart_after", AwareDateTime(), nullable=False),
        sa.Column("arrive_by", AwareDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUIRED",
                "PLANNED",
                "CONFIRMED",
                "IN_TRANSIT",
                "COMPLETED",
                "CANCELLED",
                name="movementstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "GENERATED",
                "MANUAL",
                "SUGGESTED",
                name="recordsource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "arrive_by > depart_after", name=op.f("ck_equipment_movements_date_order")
        ),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
            name=op.f("fk_equipment_movements_destination_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
            name=op.f("fk_equipment_movements_origin_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_movements")),
    )
    op.create_index(
        op.f("ix_equipment_movements_arrive_by"), "equipment_movements", ["arrive_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_movements_depart_after"),
        "equipment_movements",
        ["depart_after"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_movements_destination_location_id"),
        "equipment_movements",
        ["destination_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_movements_movement_code"),
        "equipment_movements",
        ["movement_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_equipment_movements_origin_location_id"),
        "equipment_movements",
        ["origin_location_id"],
        unique=False,
    )
    op.create_table(
        "loads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("equipment_movement_id", sa.Integer(), nullable=False),
        sa.Column("load_number", sa.Integer(), nullable=False),
        sa.Column("lorry_id", sa.Integer(), nullable=True),
        sa.Column("lorry_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PLANNED",
                "CONFIRMED",
                "LOADING",
                "DEPARTED",
                "ARRIVED",
                "UNLOADED",
                "CANCELLED",
                name="loadstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("planned_departure_at", AwareDateTime(), nullable=True),
        sa.Column("planned_arrival_at", AwareDateTime(), nullable=True),
        sa.Column("actual_departure_at", AwareDateTime(), nullable=True),
        sa.Column("actual_arrival_at", AwareDateTime(), nullable=True),
        sa.Column("driver_name", sa.String(length=150), nullable=True),
        sa.Column("estimated_distance_km", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "estimate_source",
            sa.Enum("CALCULATED", "MANUAL", name="estimatesource", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("actual_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("actual_cost >= 0", name=op.f("ck_loads_actual_cost_nonnegative")),
        sa.CheckConstraint("estimated_cost >= 0", name=op.f("ck_loads_estimated_cost_nonnegative")),
        sa.CheckConstraint("load_number > 0", name=op.f("ck_loads_load_number_positive")),
        sa.ForeignKeyConstraint(
            ["equipment_movement_id"],
            ["equipment_movements.id"],
            name=op.f("fk_loads_equipment_movement_id_equipment_movements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lorry_id"], ["lorries.id"], name=op.f("fk_loads_lorry_id_lorries")
        ),
        sa.ForeignKeyConstraint(
            ["lorry_type_id"], ["lorry_types.id"], name=op.f("fk_loads_lorry_type_id_lorry_types")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loads")),
        sa.UniqueConstraint(
            "equipment_movement_id", "load_number", name=op.f("uq_loads_equipment_movement_id")
        ),
    )
    op.create_index(
        op.f("ix_loads_equipment_movement_id"), "loads", ["equipment_movement_id"], unique=False
    )
    op.create_index(op.f("ix_loads_status"), "loads", ["status"], unique=False)
    op.create_table(
        "load_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("equipment_asset_id", sa.Integer(), nullable=True),
        sa.Column("equipment_type_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(equipment_asset_id IS NOT NULL AND equipment_type_id IS NULL AND quantity = 1) "
            "OR (equipment_asset_id IS NULL AND equipment_type_id IS NOT NULL)",
            name=op.f("ck_load_items_asset_or_quantity_type"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_load_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["equipment_asset_id"],
            ["equipment_assets.id"],
            name=op.f("fk_load_items_equipment_asset_id_equipment_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_type_id"],
            ["equipment_types.id"],
            name=op.f("fk_load_items_equipment_type_id_equipment_types"),
        ),
        sa.ForeignKeyConstraint(
            ["load_id"], ["loads.id"], name=op.f("fk_load_items_load_id_loads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_load_items")),
        sa.UniqueConstraint("load_id", "equipment_asset_id", name=op.f("uq_load_items_load_id")),
    )
    op.create_index(op.f("ix_load_items_load_id"), "load_items", ["load_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_load_items_load_id"), table_name="load_items")
    op.drop_table("load_items")
    op.drop_index(op.f("ix_loads_status"), table_name="loads")
    op.drop_index(op.f("ix_loads_equipment_movement_id"), table_name="loads")
    op.drop_table("loads")
    op.drop_index(
        op.f("ix_equipment_movements_origin_location_id"), table_name="equipment_movements"
    )
    op.drop_index(op.f("ix_equipment_movements_movement_code"), table_name="equipment_movements")
    op.drop_index(
        op.f("ix_equipment_movements_destination_location_id"), table_name="equipment_movements"
    )
    op.drop_index(op.f("ix_equipment_movements_depart_after"), table_name="equipment_movements")
    op.drop_index(op.f("ix_equipment_movements_arrive_by"), table_name="equipment_movements")
    op.drop_table("equipment_movements")
    # ### end Alembic commands ###
