"""add movement operational allowances

Revision ID: 73de560fde26
Revises: 3cd5ffa99043
Create Date: 2026-08-01 16:37:10.061633
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "73de560fde26"
down_revision: str | Sequence[str] | None = "3cd5ffa99043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment_movements",
        sa.Column("loading_minutes", sa.Integer(), server_default="60", nullable=False),
    )
    op.add_column(
        "equipment_movements",
        sa.Column("unloading_minutes", sa.Integer(), server_default="60", nullable=False),
    )
    op.add_column(
        "equipment_movements",
        sa.Column("contingency_minutes", sa.Integer(), server_default="0", nullable=False),
    )
    with op.batch_alter_table("equipment_movements") as batch_op:
        batch_op.create_check_constraint(
            op.f("ck_equipment_movements_loading_nonnegative"), "loading_minutes >= 0"
        )
        batch_op.create_check_constraint(
            op.f("ck_equipment_movements_unloading_nonnegative"), "unloading_minutes >= 0"
        )
        batch_op.create_check_constraint(
            op.f("ck_equipment_movements_contingency_nonnegative"), "contingency_minutes >= 0"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment_movements") as batch_op:
        batch_op.drop_constraint(
            op.f("ck_equipment_movements_contingency_nonnegative"), type_="check"
        )
        batch_op.drop_constraint(
            op.f("ck_equipment_movements_unloading_nonnegative"), type_="check"
        )
        batch_op.drop_constraint(op.f("ck_equipment_movements_loading_nonnegative"), type_="check")
        batch_op.drop_column("contingency_minutes")
        batch_op.drop_column("unloading_minutes")
        batch_op.drop_column("loading_minutes")
    # ### end Alembic commands ###
