"""add equipment allocation

Revision ID: 8ffe2eede605
Revises: ba06f61ec798
Create Date: 2026-08-01 16:08:20.148265
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ffe2eede605"
down_revision: str | Sequence[str] | None = "ba06f61ec798"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment_compatibility",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("required_equipment_type_id", sa.Integer(), nullable=False),
        sa.Column("compatible_equipment_type_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "required_equipment_type_id != compatible_equipment_type_id",
            name=op.f("ck_equipment_compatibility_different_types"),
        ),
        sa.ForeignKeyConstraint(
            ["compatible_equipment_type_id"],
            ["equipment_types.id"],
            name=op.f("fk_equipment_compatibility_compatible_equipment_type_id_equipment_types"),
        ),
        sa.ForeignKeyConstraint(
            ["required_equipment_type_id"],
            ["equipment_types.id"],
            name=op.f("fk_equipment_compatibility_required_equipment_type_id_equipment_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_compatibility")),
        sa.UniqueConstraint(
            "required_equipment_type_id",
            "compatible_equipment_type_id",
            name=op.f("uq_equipment_compatibility_required_equipment_type_id"),
        ),
    )
    op.create_table(
        "equipment_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_equipment_requirement_id", sa.Integer(), nullable=False),
        sa.Column("equipment_asset_id", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "allocation_strength",
            sa.Enum("SOFT", "HARD", name="allocationstrength", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column(
            "assignment_source",
            sa.Enum(
                "GENERATED",
                "MANUAL",
                "SUGGESTED",
                name="recordsource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELLED", name="assignmentstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_equipment_assignments_date_order")),
        sa.ForeignKeyConstraint(
            ["equipment_asset_id"],
            ["equipment_assets.id"],
            name=op.f("fk_equipment_assignments_equipment_asset_id_equipment_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["job_equipment_requirement_id"],
            ["job_equipment_requirements.id"],
            name=op.f(
                "fk_equipment_assignments_job_equipment_requirement_id_job_equipment_requirements"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_assignments")),
        sa.UniqueConstraint(
            "job_equipment_requirement_id",
            "equipment_asset_id",
            name=op.f("uq_equipment_assignments_job_equipment_requirement_id"),
        ),
    )
    op.create_index(
        op.f("ix_equipment_assignments_allocation_strength"),
        "equipment_assignments",
        ["allocation_strength"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_assignments_end_at"), "equipment_assignments", ["end_at"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_assignments_equipment_asset_id"),
        "equipment_assignments",
        ["equipment_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_assignments_job_equipment_requirement_id"),
        "equipment_assignments",
        ["job_equipment_requirement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_assignments_start_at"),
        "equipment_assignments",
        ["start_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_equipment_assignments_start_at"), table_name="equipment_assignments")
    op.drop_index(
        op.f("ix_equipment_assignments_job_equipment_requirement_id"),
        table_name="equipment_assignments",
    )
    op.drop_index(
        op.f("ix_equipment_assignments_equipment_asset_id"), table_name="equipment_assignments"
    )
    op.drop_index(op.f("ix_equipment_assignments_end_at"), table_name="equipment_assignments")
    op.drop_index(
        op.f("ix_equipment_assignments_allocation_strength"), table_name="equipment_assignments"
    )
    op.drop_table("equipment_assignments")
    op.drop_table("equipment_compatibility")
    # ### end Alembic commands ###
