"""add crew movements and costing

Revision ID: 91599a842340
Revises: 63dda1ae9a9e
Create Date: 2026-08-01 16:24:49.026418
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.database import AwareDateTime

revision: str = "91599a842340"
down_revision: str | Sequence[str] | None = "63dda1ae9a9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_reference", sa.String(length=100), nullable=False),
        sa.Column("haulier_id", sa.Integer(), nullable=True),
        sa.Column("supplier_name", sa.String(length=200), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("received_at", AwareDateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_supplier_invoices_total_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["haulier_id"], ["hauliers.id"], name=op.f("fk_supplier_invoices_haulier_id_hauliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_invoices")),
        sa.UniqueConstraint(
            "supplier_reference", name=op.f("uq_supplier_invoices_supplier_reference")
        ),
    )
    op.create_index(
        op.f("ix_supplier_invoices_supplier_reference"),
        "supplier_invoices",
        ["supplier_reference"],
        unique=True,
    )
    op.create_table(
        "crew_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("movement_code", sa.String(length=50), nullable=False),
        sa.Column("origin_location_id", sa.Integer(), nullable=False),
        sa.Column("destination_location_id", sa.Integer(), nullable=False),
        sa.Column("tentmaster_id", sa.Integer(), nullable=True),
        sa.Column("van_id", sa.Integer(), nullable=True),
        sa.Column("depart_after", AwareDateTime(), nullable=False),
        sa.Column("arrive_by", AwareDateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUIRED",
                "PLANNED",
                "CONFIRMED",
                "IN_TRANSIT",
                "COMPLETED",
                "CANCELLED",
                name="movementstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("arrive_by > depart_after", name=op.f("ck_crew_movements_date_order")),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
            name=op.f("fk_crew_movements_destination_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
            name=op.f("fk_crew_movements_origin_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_crew_movements_tentmaster_id_tentmasters"),
        ),
        sa.ForeignKeyConstraint(
            ["van_id"], ["vans.id"], name=op.f("fk_crew_movements_van_id_vans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_movements")),
    )
    op.create_index(
        op.f("ix_crew_movements_arrive_by"), "crew_movements", ["arrive_by"], unique=False
    )
    op.create_index(
        op.f("ix_crew_movements_depart_after"), "crew_movements", ["depart_after"], unique=False
    )
    op.create_index(
        op.f("ix_crew_movements_destination_location_id"),
        "crew_movements",
        ["destination_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crew_movements_movement_code"), "crew_movements", ["movement_code"], unique=True
    )
    op.create_index(
        op.f("ix_crew_movements_origin_location_id"),
        "crew_movements",
        ["origin_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crew_movements_tentmaster_id"), "crew_movements", ["tentmaster_id"], unique=False
    )
    op.create_table(
        "load_cost_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_invoice_id", sa.Integer(), nullable=False),
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("allocated_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "allocated_amount >= 0", name=op.f("ck_load_cost_allocations_amount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_load_cost_allocations_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["load_id"], ["loads.id"], name=op.f("fk_load_cost_allocations_load_id_loads")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_invoice_id"],
            ["supplier_invoices.id"],
            name=op.f("fk_load_cost_allocations_supplier_invoice_id_supplier_invoices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_load_cost_allocations")),
        sa.UniqueConstraint(
            "supplier_invoice_id",
            "load_id",
            "job_id",
            "category",
            name=op.f("uq_load_cost_allocations_supplier_invoice_id"),
        ),
    )
    op.create_index(
        op.f("ix_load_cost_allocations_job_id"), "load_cost_allocations", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_load_cost_allocations_load_id"), "load_cost_allocations", ["load_id"], unique=False
    )
    op.create_index(
        op.f("ix_load_cost_allocations_supplier_invoice_id"),
        "load_cost_allocations",
        ["supplier_invoice_id"],
        unique=False,
    )
    op.create_table(
        "crew_journey_legs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crew_movement_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "VAN",
                "LORRY",
                "FLIGHT",
                "FERRY",
                "TRAIN",
                "TRANSFER",
                "OTHER",
                name="journeymode",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("origin_label", sa.String(length=200), nullable=False),
        sa.Column("destination_label", sa.String(length=200), nullable=False),
        sa.Column("depart_at", AwareDateTime(), nullable=False),
        sa.Column("arrive_at", AwareDateTime(), nullable=False),
        sa.Column("booking_reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("arrive_at > depart_at", name=op.f("ck_crew_journey_legs_date_order")),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_crew_journey_legs_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["crew_movement_id"],
            ["crew_movements.id"],
            name=op.f("fk_crew_journey_legs_crew_movement_id_crew_movements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_journey_legs")),
        sa.UniqueConstraint(
            "crew_movement_id", "sequence", name=op.f("uq_crew_journey_legs_crew_movement_id")
        ),
    )
    op.create_index(
        op.f("ix_crew_journey_legs_crew_movement_id"),
        "crew_journey_legs",
        ["crew_movement_id"],
        unique=False,
    )
    op.create_table(
        "crew_movement_passengers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crew_movement_id", sa.Integer(), nullable=False),
        sa.Column("crew_member_id", sa.Integer(), nullable=True),
        sa.Column("placeholder_label", sa.String(length=150), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("joining_tentmaster_id", sa.Integer(), nullable=True),
        sa.Column("leaving_tentmaster_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(crew_member_id IS NOT NULL AND placeholder_label IS NULL AND quantity = 1) "
            "OR (crew_member_id IS NULL AND placeholder_label IS NOT NULL)",
            name=op.f("ck_crew_movement_passengers_named_or_placeholder"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_crew_movement_passengers_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_crew_movement_passengers_crew_member_id_crew_members"),
        ),
        sa.ForeignKeyConstraint(
            ["crew_movement_id"],
            ["crew_movements.id"],
            name=op.f("fk_crew_movement_passengers_crew_movement_id_crew_movements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["joining_tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_crew_movement_passengers_joining_tentmaster_id_tentmasters"),
        ),
        sa.ForeignKeyConstraint(
            ["leaving_tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_crew_movement_passengers_leaving_tentmaster_id_tentmasters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_movement_passengers")),
        sa.UniqueConstraint(
            "crew_movement_id",
            "crew_member_id",
            name=op.f("uq_crew_movement_passengers_crew_movement_id"),
        ),
    )
    op.create_index(
        op.f("ix_crew_movement_passengers_crew_movement_id"),
        "crew_movement_passengers",
        ["crew_movement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_crew_movement_passengers_crew_movement_id"), table_name="crew_movement_passengers"
    )
    op.drop_table("crew_movement_passengers")
    op.drop_index(op.f("ix_crew_journey_legs_crew_movement_id"), table_name="crew_journey_legs")
    op.drop_table("crew_journey_legs")
    op.drop_index(
        op.f("ix_load_cost_allocations_supplier_invoice_id"), table_name="load_cost_allocations"
    )
    op.drop_index(op.f("ix_load_cost_allocations_load_id"), table_name="load_cost_allocations")
    op.drop_index(op.f("ix_load_cost_allocations_job_id"), table_name="load_cost_allocations")
    op.drop_table("load_cost_allocations")
    op.drop_index(op.f("ix_crew_movements_tentmaster_id"), table_name="crew_movements")
    op.drop_index(op.f("ix_crew_movements_origin_location_id"), table_name="crew_movements")
    op.drop_index(op.f("ix_crew_movements_movement_code"), table_name="crew_movements")
    op.drop_index(op.f("ix_crew_movements_destination_location_id"), table_name="crew_movements")
    op.drop_index(op.f("ix_crew_movements_depart_after"), table_name="crew_movements")
    op.drop_index(op.f("ix_crew_movements_arrive_by"), table_name="crew_movements")
    op.drop_table("crew_movements")
    op.drop_index(op.f("ix_supplier_invoices_supplier_reference"), table_name="supplier_invoices")
    op.drop_table("supplier_invoices")
    # ### end Alembic commands ###
