"""add crew planning

Revision ID: ba06f61ec798
Revises: 2afbf5e551ad
Create Date: 2026-08-01 16:04:12.885568
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ba06f61ec798"
down_revision: str | Sequence[str] | None = "2afbf5e551ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "TRAINING",
                "LEAVE",
                "YARD_WORK",
                "TRAVEL",
                "OTHER",
                name="crewactivitytype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("tentmaster_id", sa.Integer(), nullable=True),
        sa.Column("crew_member_id", sa.Integer(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("required_headcount", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_crew_activities_date_order")),
        sa.CheckConstraint(
            "required_headcount >= 0", name=op.f("ck_crew_activities_headcount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_crew_activities_crew_member_id_crew_members"),
        ),
        sa.ForeignKeyConstraint(
            ["tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_crew_activities_tentmaster_id_tentmasters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_activities")),
    )
    op.create_index(
        op.f("ix_crew_activities_activity_type"), "crew_activities", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("ix_crew_activities_crew_member_id"),
        "crew_activities",
        ["crew_member_id"],
        unique=False,
    )
    op.create_index(op.f("ix_crew_activities_end_at"), "crew_activities", ["end_at"], unique=False)
    op.create_index(
        op.f("ix_crew_activities_start_at"), "crew_activities", ["start_at"], unique=False
    )
    op.create_index(
        op.f("ix_crew_activities_tentmaster_id"), "crew_activities", ["tentmaster_id"], unique=False
    )
    op.create_table(
        "crew_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_phase_id", sa.Integer(), nullable=False),
        sa.Column("crew_member_id", sa.Integer(), nullable=True),
        sa.Column("placeholder_name", sa.String(length=150), nullable=True),
        sa.Column("tentmaster_id", sa.Integer(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column(
            "assignment_source",
            sa.Enum(
                "GENERATED",
                "MANUAL",
                "SUGGESTED",
                name="recordsource",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("hourly_cost_override", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(crew_member_id IS NOT NULL AND placeholder_name IS NULL) OR "
            "(crew_member_id IS NULL AND placeholder_name IS NOT NULL)",
            name=op.f("ck_crew_assignments_person_or_placeholder"),
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_crew_assignments_date_order")),
        sa.CheckConstraint(
            "hourly_cost_override IS NULL OR hourly_cost_override >= 0",
            name=op.f("ck_crew_assignments_hourly_cost_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_crew_assignments_crew_member_id_crew_members"),
        ),
        sa.ForeignKeyConstraint(
            ["job_phase_id"],
            ["job_phases.id"],
            name=op.f("fk_crew_assignments_job_phase_id_job_phases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tentmaster_id"],
            ["tentmasters.id"],
            name=op.f("fk_crew_assignments_tentmaster_id_tentmasters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_assignments")),
    )
    op.create_index(
        op.f("ix_crew_assignments_crew_member_id"),
        "crew_assignments",
        ["crew_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crew_assignments_end_at"), "crew_assignments", ["end_at"], unique=False
    )
    op.create_index(
        op.f("ix_crew_assignments_job_phase_id"), "crew_assignments", ["job_phase_id"], unique=False
    )
    op.create_index(
        op.f("ix_crew_assignments_start_at"), "crew_assignments", ["start_at"], unique=False
    )
    op.create_index(
        op.f("ix_crew_assignments_tentmaster_id"),
        "crew_assignments",
        ["tentmaster_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crew_assignments_tentmaster_id"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_start_at"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_job_phase_id"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_end_at"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_crew_member_id"), table_name="crew_assignments")
    op.drop_table("crew_assignments")
    op.drop_index(op.f("ix_crew_activities_tentmaster_id"), table_name="crew_activities")
    op.drop_index(op.f("ix_crew_activities_start_at"), table_name="crew_activities")
    op.drop_index(op.f("ix_crew_activities_end_at"), table_name="crew_activities")
    op.drop_index(op.f("ix_crew_activities_crew_member_id"), table_name="crew_activities")
    op.drop_index(op.f("ix_crew_activities_activity_type"), table_name="crew_activities")
    op.drop_table("crew_activities")
    # ### end Alembic commands ###
