"""operational phases rework

Revision ID: e71a563ebf28
Revises: 47d2b2d36c51
Create Date: 2026-08-03 14:00:05.860391
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.database import AwareDateTime

revision: str = "e71a563ebf28"
down_revision: str | Sequence[str] | None = "47d2b2d36c51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # 1. New table for local/hired headcount booked directly onto a job over a date range.
    op.create_table(
        "local_crew_bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("headcount", sa.Integer(), nullable=False),
        sa.Column("start_at", AwareDateTime(), nullable=False),
        sa.Column("end_at", AwareDateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_local_crew_bookings_date_order")),
        sa.CheckConstraint(
            "headcount > 0", name=op.f("ck_local_crew_bookings_headcount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_local_crew_bookings_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local_crew_bookings")),
    )
    op.create_index(
        op.f("ix_local_crew_bookings_end_at"), "local_crew_bookings", ["end_at"], unique=False
    )
    op.create_index(
        op.f("ix_local_crew_bookings_job_id"), "local_crew_bookings", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_local_crew_bookings_start_at"), "local_crew_bookings", ["start_at"], unique=False
    )

    # 2. Add the new (nullable-for-now) columns so existing rows can be backfilled before either
    #    becomes required.
    op.add_column(
        "job_tent_requirements", sa.Column("contracted_up_at", AwareDateTime(), nullable=True)
    )
    op.add_column(
        "job_tent_requirements", sa.Column("contracted_down_at", AwareDateTime(), nullable=True)
    )
    op.add_column(
        "job_phases", sa.Column("job_tent_requirement_id", sa.Integer(), nullable=True)
    )
    with op.batch_alter_table("job_phases") as batch_op:
        batch_op.create_index(
            op.f("ix_job_phases_job_tent_requirement_id"),
            ["job_tent_requirement_id"],
        )
        batch_op.create_foreign_key(
            op.f("fk_job_phases_job_tent_requirement_id_job_tent_requirements"),
            "job_tent_requirements",
            ["job_tent_requirement_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # 3. Backfill every tent's contract dates from its job's old must_be_up_at/strike_available_at
    #    — the old model had one shared Up/Down per job; every tent on that job gets those same
    #    starting values here (the planner can't change the old data's shape retroactively, but
    #    this preserves the real dates that existed rather than guessing).
    bind.execute(
        sa.text(
            "UPDATE job_tent_requirements SET "
            "contracted_up_at = ("
            "  SELECT must_be_up_at FROM jobs WHERE jobs.id = job_tent_requirements.job_id"
            "), "
            "contracted_down_at = ("
            "  SELECT strike_available_at FROM jobs WHERE jobs.id = job_tent_requirements.job_id"
            ")"
        )
    )

    # 4. Reclassify existing phases: SHOW -> UP, tied to the job's first (lowest-id) tent, since
    #    the old model had one shared Up window per job rather than one per tent. STRIKE -> BREAK.
    #    SITE_PREP/HANDOVER/MAINTENANCE/CLEAR_SITE were never actually auto-generated by the old
    #    code, but if any exist (manually created), fold them into OTHER rather than leaving a
    #    phase_type value the app no longer understands.
    first_tent_by_job = dict(
        bind.execute(
            sa.text("SELECT job_id, MIN(id) FROM job_tent_requirements GROUP BY job_id")
        ).all()
    )
    for job_id, tent_id in first_tent_by_job.items():
        bind.execute(
            sa.text(
                "UPDATE job_phases SET phase_type = 'UP', job_tent_requirement_id = :tent_id "
                "WHERE job_id = :job_id AND phase_type = 'SHOW'"
            ),
            {"tent_id": tent_id, "job_id": job_id},
        )
    bind.execute(sa.text("UPDATE job_phases SET phase_type = 'BREAK' WHERE phase_type = 'STRIKE'"))
    bind.execute(
        sa.text(
            "UPDATE job_phases SET phase_type = 'OTHER' "
            "WHERE phase_type IN ('SITE_PREP', 'HANDOVER', 'MAINTENANCE', 'CLEAR_SITE')"
        )
    )

    # 5. Preserve real local-crew data before it's dropped: placeholder CrewAssignment rows become
    #    LocalCrewBooking rows (headcount 1 each); a job's flat local_crew_supplied count becomes
    #    one booking spanning that job's full phase window. Named ADD/EXCLUDE overrides have no
    #    equivalent in the new model (D036) and are not migrated — the override mechanism itself
    #    is being removed, not replaced.
    placeholder_rows = bind.execute(
        sa.text(
            "SELECT ca.start_at, ca.end_at, ca.notes, jp.job_id "
            "FROM crew_assignments ca JOIN job_phases jp ON jp.id = ca.job_phase_id "
            "WHERE ca.placeholder_name IS NOT NULL"
        )
    ).all()
    for start_at, end_at, notes, job_id in placeholder_rows:
        bind.execute(
            sa.text(
                "INSERT INTO local_crew_bookings (job_id, headcount, start_at, end_at, notes) "
                "VALUES (:job_id, 1, :start_at, :end_at, :notes)"
            ),
            {"job_id": job_id, "start_at": start_at, "end_at": end_at, "notes": notes},
        )

    supplied_jobs = bind.execute(
        sa.text("SELECT id, local_crew_supplied FROM jobs WHERE local_crew_supplied > 0")
    ).all()
    for job_id, headcount in supplied_jobs:
        window = bind.execute(
            sa.text("SELECT MIN(start_at), MAX(end_at) FROM job_phases WHERE job_id = :job_id"),
            {"job_id": job_id},
        ).one()
        if window[0] is None:
            continue
        bind.execute(
            sa.text(
                "INSERT INTO local_crew_bookings (job_id, headcount, start_at, end_at, notes) "
                "VALUES (:job_id, :headcount, :start_at, :end_at, "
                "'Migrated from the old local_crew_supplied field')"
            ),
            {
                "job_id": job_id,
                "headcount": headcount,
                "start_at": window[0],
                "end_at": window[1],
            },
        )

    # 6. Drop the override mechanism entirely.
    op.drop_index(op.f("ix_crew_assignments_crew_member_id"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_end_at"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_job_phase_id"), table_name="crew_assignments")
    op.drop_index(op.f("ix_crew_assignments_start_at"), table_name="crew_assignments")
    op.drop_table("crew_assignments")

    # 7. Now that every tent has contract dates, make them required, index them, and add the
    #    tent<->Up correspondence check; drop the old per-tent override columns (unused in real
    #    data — confirmed by inspecting instance/kayam.db before writing this migration).
    with op.batch_alter_table("job_tent_requirements") as batch_op:
        batch_op.drop_column("required_crew_override")
        batch_op.drop_column("build_duration_override_hours")
        batch_op.drop_column("strike_duration_override_hours")
        batch_op.drop_column("build_start_override")
        batch_op.alter_column("contracted_up_at", existing_type=AwareDateTime(), nullable=False)
        batch_op.alter_column("contracted_down_at", existing_type=AwareDateTime(), nullable=False)
        batch_op.create_index(
            op.f("ix_job_tent_requirements_contracted_down_at"), ["contracted_down_at"]
        )
        batch_op.create_index(
            op.f("ix_job_tent_requirements_contracted_up_at"), ["contracted_up_at"]
        )
        batch_op.create_check_constraint(
            op.f("ck_job_tent_requirements_contract_date_order"),
            "contracted_down_at > contracted_up_at",
        )

    with op.batch_alter_table("job_phases") as batch_op:
        batch_op.create_check_constraint(
            op.f("ck_job_phases_up_requires_tent"),
            "phase_type != 'UP' OR job_tent_requirement_id IS NOT NULL",
        )
        batch_op.create_check_constraint(
            op.f("ck_job_phases_only_up_has_tent"),
            "phase_type = 'UP' OR job_tent_requirement_id IS NULL",
        )

    # 8. Jobs: contract dates moved to tents, local crew moved to bookings — drop the old columns
    #    and constraints; Access becomes optional (general, job-wide, no longer required).
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.drop_constraint(op.f("ck_jobs_access_before_up"), type_="check")
        batch_op.drop_constraint(op.f("ck_jobs_up_before_strike"), type_="check")
        batch_op.drop_constraint(op.f("ck_jobs_show_date_order"), type_="check")
        batch_op.drop_constraint(op.f("ck_jobs_strike_before_clear"), type_="check")
        batch_op.drop_constraint(op.f("ck_jobs_local_crew_required_nonnegative"), type_="check")
        batch_op.drop_constraint(op.f("ck_jobs_local_crew_supplied_nonnegative"), type_="check")
        batch_op.drop_index(op.f("ix_jobs_strike_available_at"))
        batch_op.drop_column("must_be_up_at")
        batch_op.drop_column("show_start_at")
        batch_op.drop_column("show_end_at")
        batch_op.drop_column("strike_available_at")
        batch_op.drop_column("local_crew_supplied")
        batch_op.drop_column("local_crew_required")
        batch_op.alter_column("site_access_at", existing_type=AwareDateTime(), nullable=True)
        batch_op.create_check_constraint(
            op.f("ck_jobs_clear_after_access"),
            "site_clear_by IS NULL OR site_access_at IS NULL OR site_clear_by >= site_access_at",
        )


def downgrade() -> None:
    """Downgrade schema.

    Best-effort structural reversal only — local crew bookings and the Show/Strike phase
    reclassification are not reversed, since there's no lossless way back (multiple tents on one
    job may now have diverged contract dates that a single job-level Up/Down can't represent).
    """
    with op.batch_alter_table("jobs") as batch_op:
        batch_op.drop_constraint(op.f("ck_jobs_clear_after_access"), type_="check")
        batch_op.alter_column("site_access_at", existing_type=AwareDateTime(), nullable=False)
        batch_op.add_column(
            sa.Column(
                "local_crew_required", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "local_crew_supplied", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(sa.Column("strike_available_at", AwareDateTime(), nullable=True))
        batch_op.add_column(sa.Column("show_end_at", AwareDateTime(), nullable=True))
        batch_op.add_column(sa.Column("show_start_at", AwareDateTime(), nullable=True))
        batch_op.add_column(sa.Column("must_be_up_at", AwareDateTime(), nullable=True))

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "UPDATE jobs SET "
            "must_be_up_at = ("
            "  SELECT MIN(contracted_up_at) FROM job_tent_requirements WHERE job_id = jobs.id"
            "), "
            "strike_available_at = ("
            "  SELECT MAX(contracted_down_at) FROM job_tent_requirements WHERE job_id = jobs.id"
            ")"
        )
    )
    bind.execute(
        sa.text(
            "UPDATE jobs SET strike_available_at = site_access_at "
            "WHERE strike_available_at IS NULL"
        )
    )
    bind.execute(
        sa.text("UPDATE jobs SET must_be_up_at = site_access_at WHERE must_be_up_at IS NULL")
    )

    with op.batch_alter_table("jobs") as batch_op:
        batch_op.alter_column("must_be_up_at", existing_type=AwareDateTime(), nullable=False)
        batch_op.alter_column("strike_available_at", existing_type=AwareDateTime(), nullable=False)
        batch_op.create_index("ix_jobs_strike_available_at", ["strike_available_at"])
        batch_op.create_check_constraint(
            op.f("ck_jobs_local_crew_supplied_nonnegative"), "local_crew_supplied >= 0"
        )
        batch_op.create_check_constraint(
            op.f("ck_jobs_local_crew_required_nonnegative"), "local_crew_required >= 0"
        )
        batch_op.create_check_constraint(
            op.f("ck_jobs_strike_before_clear"),
            "site_clear_by IS NULL OR site_clear_by >= strike_available_at",
        )
        batch_op.create_check_constraint(
            op.f("ck_jobs_show_date_order"),
            "show_end_at IS NULL OR show_start_at IS NULL OR show_end_at >= show_start_at",
        )
        batch_op.create_check_constraint(
            op.f("ck_jobs_up_before_strike"), "strike_available_at >= must_be_up_at"
        )
        batch_op.create_check_constraint(
            op.f("ck_jobs_access_before_up"), "must_be_up_at >= site_access_at"
        )

    with op.batch_alter_table("job_phases") as batch_op:
        batch_op.drop_constraint(op.f("ck_job_phases_only_up_has_tent"), type_="check")
        batch_op.drop_constraint(op.f("ck_job_phases_up_requires_tent"), type_="check")

    bind.execute(sa.text("UPDATE job_phases SET phase_type = 'SHOW' WHERE phase_type = 'UP'"))
    bind.execute(sa.text("UPDATE job_phases SET phase_type = 'STRIKE' WHERE phase_type = 'BREAK'"))

    with op.batch_alter_table("job_tent_requirements") as batch_op:
        batch_op.drop_constraint(
            op.f("ck_job_tent_requirements_contract_date_order"), type_="check"
        )
        batch_op.drop_index(op.f("ix_job_tent_requirements_contracted_up_at"))
        batch_op.drop_index(op.f("ix_job_tent_requirements_contracted_down_at"))
        batch_op.add_column(sa.Column("required_crew_override", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("strike_duration_override_hours", sa.Numeric(8, 2), nullable=True)
        )
        batch_op.add_column(
            sa.Column("build_duration_override_hours", sa.Numeric(8, 2), nullable=True)
        )
        batch_op.add_column(sa.Column("build_start_override", AwareDateTime(), nullable=True))

    with op.batch_alter_table("job_phases") as batch_op:
        batch_op.drop_constraint(
            op.f("fk_job_phases_job_tent_requirement_id_job_tent_requirements"),
            type_="foreignkey",
        )
        batch_op.drop_index(op.f("ix_job_phases_job_tent_requirement_id"))
        batch_op.drop_column("job_tent_requirement_id")
    op.drop_column("job_tent_requirements", "contracted_down_at")
    op.drop_column("job_tent_requirements", "contracted_up_at")

    op.create_table(
        "crew_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_phase_id", sa.Integer(), nullable=False),
        sa.Column("crew_member_id", sa.Integer(), nullable=True),
        sa.Column("placeholder_name", sa.String(length=150), nullable=True),
        sa.Column("start_at", AwareDateTime(), nullable=False),
        sa.Column("end_at", AwareDateTime(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("assignment_source", sa.String(length=20), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("hourly_cost_override", sa.Numeric(10, 2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("override_type", sa.String(length=10), nullable=True),
        sa.CheckConstraint(
            "hourly_cost_override IS NULL OR override_type = 'ADD'",
            name=op.f("ck_crew_assignments_hourly_override_requires_add"),
        ),
        sa.CheckConstraint(
            "(crew_member_id IS NOT NULL AND override_type IS NOT NULL) OR "
            "(crew_member_id IS NULL AND override_type IS NULL)",
            name=op.f("ck_crew_assignments_override_type_matches_person"),
        ),
        sa.CheckConstraint(
            "(crew_member_id IS NOT NULL AND placeholder_name IS NULL) OR "
            "(crew_member_id IS NULL AND placeholder_name IS NOT NULL)",
            name=op.f("ck_crew_assignments_person_or_placeholder"),
        ),
        sa.CheckConstraint("end_at > start_at", name=op.f("ck_crew_assignments_date_order")),
        sa.CheckConstraint(
            "hourly_cost_override IS NULL OR hourly_cost_override >= 0",
            name=op.f("ck_crew_assignments_hourly_cost_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["crew_member_id"],
            ["crew_members.id"],
            name=op.f("fk_crew_assignments_crew_member_id_crew_members"),
        ),
        sa.ForeignKeyConstraint(
            ["job_phase_id"],
            ["job_phases.id"],
            name=op.f("fk_crew_assignments_job_phase_id_job_phases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crew_assignments")),
        sa.UniqueConstraint(
            "job_phase_id", "crew_member_id", name=op.f("uq_crew_assignments_job_phase_id")
        ),
    )
    op.create_index(
        op.f("ix_crew_assignments_start_at"), "crew_assignments", ["start_at"], unique=False
    )
    op.create_index(
        op.f("ix_crew_assignments_job_phase_id"), "crew_assignments", ["job_phase_id"], unique=False
    )
    op.create_index(
        op.f("ix_crew_assignments_end_at"), "crew_assignments", ["end_at"], unique=False
    )
    op.create_index(
        op.f("ix_crew_assignments_crew_member_id"),
        "crew_assignments",
        ["crew_member_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_local_crew_bookings_start_at"), table_name="local_crew_bookings")
    op.drop_index(op.f("ix_local_crew_bookings_job_id"), table_name="local_crew_bookings")
    op.drop_index(op.f("ix_local_crew_bookings_end_at"), table_name="local_crew_bookings")
    op.drop_table("local_crew_bookings")
